apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metadata.fullname" . }}-api
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "metadata.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "metadata.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "metadata.fullname" . }}-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresSecret }}
                  key: password
            - name: RGW_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecret }}
                  key: access-key
            - name: RGW_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecret }}
                  key: secret-key
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
