---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: pcam
spec:
  encryptedData:
    .dockerconfigjson: AgBybnsyfqW/QAO1YQAUh9ZooekKisPrORNbUa/dkmoOKdPFgkh+XjnEYMQyr9KJHbesRFOReVc5iF1yoHBSStTw1yTRZfzJiXHhSPkgomN0OD7oQ/dscRi5saleSCi+60YdHSVWui9Vyklgjc8J3U62P1P7m0MLKd1i5yHKm2Uy5Lo5MqKdgrDvru5B5kbvB0/bRd5AIVSIr/LA4okn+If6EWUlwl63D6atLQKoJ18K6Y33v6LRmdQPvW6WVECHau94JL/kglNtWEj5ngkmBiAyvzNao0rPZfooHvrDWJtcI4KAVxzPNWr8bac4fkQJUBlBjJBMiCt3IZUUaHaqpuLynkFObhhjvMg+G1uDEKs5Xewwx4COVzEdUOuWArNNZGGwP6VOu1mnUQUb7rsBFZUJAcspXls/ji70hAcnRxoO3uOlHQiDl9gqNm5YOvJt422wjjYAvdl579PKdcleIYjhphcxzObgkm48vBxL4lTL2+guZCzGLSaIFDD+asYkQB0iVD9uRC4Q+W3ae+DFeKbABV/Grk32zQy03rqSQzSJhbAoJxhhMSs83UeABcZqulRjsAChUrai1ARvzrCth7S2XvNOXkdrHw0RL6FF6Q/NhInjTmH/115JbeLWJ6pn8WrijKXFQwQhNP/2ZftJs93KVVruVU7z7IBnpHUaSaGvV6SUWteKUL/CpJSmLwU4ZofLenowjg0Mq21HoyYsjixQyrOvbzwC/heuwt4/jG8e46FXa/RcArjQotKYcEcNj+U3Q5wc+0Npv+HCaY+OUGLDN/qhK/bWhUWmjPWqcZ0QR6Ko2FMR37aYEGpX2Xh76Yq0Uc47dIgM1Mqkb2xXtwT2B5GUDFsk07uU9e1Eyr3sPi4PNVjud1tkDJwM07tokQwDh3VkzUuivZNK3X/y0EGZ7n/m41hOvatbYkuh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: pcam
    type: kubernetes.io/dockerconfigjson
