---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: pcam
spec:
  encryptedData:
    .dockerconfigjson: AgCf9JGgBfArpCABOgNmVaXRw+b+6og+kYNFbkCtu7Nj/isN0QdeC2aMyKqWYAy7eA7gkqnBPHf5Z7ZW2+jl8zNQBX5E5icTU/uzIosd1BsBt3sPDllRAMQFiXpKb2Ui/VHa5xdaeRZHXg9GZy4c9lCOwtPcB0U6zx43gyolhX7+swlOnIW1B+2cJ9ksxVGH3u6UOoJX5Z0VoZlylgxwc7C13HZalLKtZCiN9GgryCgTm4KmE3qD8f3gGAvX/+HVjOFljjOw0en4+vbee25FnmRjnN85BeUhN/SSV+nYy0T87MI0nB9qzy1aIlgj0lvMmgH8H7eiiu2V40/RUZ60ath/NLt2ajqrUPIRht2sCfrUcHY64NxT9OFyvVCrJCmek3TFLJzD5IKs2XalmCp1OZ99/LIjIHjHFSe50t4MXbqt677NYYRSxeYLVBFMNsy+mWuCVO6+JXCj+W3UXLuaYVD/knkP6+kH1fJSOoqjbBDOhMo8ClL84vkJfMcK7CLNQMUcMz3FvMADZMSTQ9Pyw0UAZPYFlsOBmSusuzHkyDlFPIXXPzg60VKtFQ1sHG4QpzSNP0tLGyvlyUmv2F4ZmZkrKuKoYLcomHTqAvYjA8PkS9BPSXur4IPHxU93vwe3phMP0zYWdyMCg4JY/57xxbsKoyihmDcJsSOMIcW2Lxo2Of65N5w4nMPfoQ92pTb6HBExG6g0Bwt2jQKO5Y9ky8kXZqi2dA3cyJu1VEyHo7i/YthTjdNKQlgiZFyVYzxZxPYuDXV8SfQXGFQlJa1Gfh1r7acTPSIYsMYuICnrwPA2HtwDvLph9/VpJqp4IQG7LfRw07tf41ulSWKo/j0qKXgRsBDoU3EagOZ3OP2JSmxvesmb8Jm1LOYI2lJo31eWcG9YJTaHhKPPZfjYx0XOZSoUzDr5bn1+Ul0/aIgC
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: pcam
    type: kubernetes.io/dockerconfigjson
