---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pcam-rgw-credentials
  namespace: pcam
spec:
  encryptedData:
    access-key: AgBvdWhTM7j90Oz/LeN0sD5cR3X4qF5f1VxPR/AQG6gUe3A5/UEWPkS99N75woqQG3xqJiMAC6sXMIV6rTSgMd17hUG70c7eHr2rBAEZ3az3oadLtYpLOMX+iKyF4GSLURqGH/TWpHEOHRHLRynw0CA9keYEMRzb1ltvXMy+Sj0j3qvH6jLgXcg60BVMOGkPIFA/fONLm00H8XQCWSGydQwmA3XKjzTGJ+2IwUJjhJ/fy5s7cvbnRR3JY+mS0VhLQwkQCRDkf9vAaG3r6B79i1Q8Wh96Ce5wjT2cz7eU1JzkKGnj/D78GcgftIeXR6YDGEnhql8krS8cZygBIibF8Th48aYzngliGIk/F1KFqvvTVO5mGWTexoXJtY1riS3jb+puW/EB4pZBwM+TK3HGtxV1iwJxsUaW/ApvD2m+f5O8lAhSkTIwd8Npy00ywcdIRaX63G3Q2XBWUYYWGcj8P/c3/OlezPFGwi8BBqIGbmVs8FQhPy1XshJ2/jZepjh7rf3ZQ+l8SiYmk8Esv2muoq148166168qLNtdS0oEfsDnSv+yjll/ogikAWrNYcxzkIUCSvvyYA+4cFXCLMgmOxQFTCb0rmeKdxf9vdzCToejrVOofVSDZ0TOCcnWhMKchE97dGU+7E2hNxqbZ/I8YByLEh2Jz+GDGi0gO2EPJEJDHJ+FKyGXNAzDvPJlHNTyv6RFnsWVTawsToQKl0wJ343qjsfb1g==
    secret-key: AgBQ7TgfbCY2S0GuoVGyzti3GKDOHI2To/Zeuzsh3MzY7ILxPWr87VNZMYCjVowiRdyu4iq8N57hEKz+EiKZ9ou1PvIyh4tkwFZKd1ninHnIS42Zf8xr7HBRG3ej69FZWFdxzPGjrJJNuTBUSKfc1lVrVHbw54KdTHCuke+Or6q6uzEZ4Ec8TyrPN0hvWDXJeOJjQ7fu5mBVgyxPP4lzKkd0DBYt82rQYBYBpiPXLazeshPYhazVBo3XYn5sV1aFsaK/zIZXAonn1yNM5k4I8RZep68xdDY9nB5HMxRsHBVbmJFRDpg7GsPIJEY/lnO0yTRnergv9FCctR32Bqj9xOof/opvi9hXsWzP4IoZmSi6ew3O7kzmYppIZ6wqSvK1D09kwkUo5Cbyac881XKfT/AZnf5YvHaYV34B9/Vc0UF1GiPpWa/RqqSuLiVAyQpM1Hmj9CjCRARVA8y5mIA8jH2c9dX+ukwIIpQgSRkcTVgn1fB8xvbejF8+ZI212cCX3H3d0msoKbc0BAy3FPpvJgsY0WcModHJN5kajTVYhwUeUYzdYGQl7fUZLBW7oNrEyG6GnKuTxtsbdvHAih/skElkThPS19SfBbe7UaK2XRJVmyynFYazbB4Lr56pO7MMnGyTXhfY0Ot+1jja9NjAmmUEk1lYEYS7eWis5H7wO7yt0kiqoUaXkdjgP/0GbD+KyBHawZv75NuAavWEJAWoj7hjeNU1WLUWTW9qG8TG5NbcwgBcnFIUNmQx
  template:
    metadata:
      creationTimestamp: null
      name: pcam-rgw-credentials
      namespace: pcam
