apiVersion: v1
kind: ServiceAccount
metadata:
  name: p8-benchmark
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: p8-benchmark
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: p8-benchmark
  namespace: default
subjects:
  - kind: ServiceAccount
    name: p8-benchmark
    namespace: default
roleRef:
  kind: Role
  name: p8-benchmark
  apiGroup: rbac.authorization.k8s.io
