apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nlp-inference
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahembal/portfolio
    targetRevision: main
    path: p4-nlp-deployment/helm/nlp-inference
  destination:
    server: https://kubernetes.default.svc
    namespace: nlp-inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
