---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nlp-inference-secrets
  namespace: nlp-inference
spec:
  encryptedData:
    RGW_ACCESS_KEY: AgAfFG6uLWoHOTe+7d72WiZ9+3C7EUcsra4Hy+3Hjq9ehUo7fa0l3ziVidUviJNDP0Zkg1TNed2Exo8ohk+3Yn/ZykfZdrWW39IDH0utzRWEBDFt/EebGR4CvPUEvL4cNc0RyLvP7WBhAHbvL/y2oe3C5xhFMff/Z6nIcbG3YyALaxf62SwiD1d8lhBogLcwFSkFVA4KigOrWNCbf12doAxCHPTwQwlUTpI88FMJuY7hFFZDIIG3fvJw96MJbkJbKVUoVpEnN9AUvmh1V1+Tpc7IGaa8YCQZoWorQbedG9uklrAvoChb30qxIpRcvdQP7GPSwsDL1jxz0m7AkWPIlFzklXI8/peq54qbzcO4w00zsKZ5zp2Bu7JSoianXG3gtvLQX10+gnfgcy8dnnoLdlQst5Eojh92S+toId61WwCXoT9VXA2OIcwc+zPyIYzLiJlvO6IAKTPhW8fFA+GUY15T8hO9THGeQHASNRZDM3kWTUd2alzCzkq4R88z+hwWmKOcjbUKwmF33VhW9kw8z1ara4RWfJobSN9zPANfuRRdhW4e9IkLekTEHYdVA35FrulZgLaZ+coDGCLSXEB3d/C2HGaYYiPgi9EQKBAQLWNVDW0X0Tq6+z1out2XHbt2aPQwUZAxpuZs+M1f432KCaw01GQyK2fB3lRvREf2+k1WvH5kJZiIm84j7T7VK94SqvfHHsWs6iIePjrxLX9LVRlJidYsVw==
    RGW_SECRET_KEY: AgBZ0lP+Yb/K1l2DCz6zN8PA6aXowvkfaZaqgeWKVZLVP6w1/gSTNamaYT97udnDtz2HMOijdyFQjxCc1+Voc37DIP1Tg9GM95wJnYt41Q2Auden1s9TUjsTb8XPT5m80KwxgI2xIVcddEP85D5sB5+XwJYqzl9XTg8BfHDLzEYQe3jsliPodT2/VIUYzzV1VBcYA8gWeVUBYZLViQ6k29py1ec5HKVPTNFdH3h6fE3u7VYpjxWqGH5Le75BeKzXTaB0s/0xiMmGdalkabPHwvazK34XYc0K8C9SRlnu9ZVPSAaaMZfGSQ0A7KfZYaz0kl6F0Jyr/wmHo7g0jzc4oJAQJOe5TLJ6M30qoG5dEj4PP8DJM55ZgR+HscAJLkp1EBuMZIszHREZeucJGnLARwsdpxU+Kf4snrXdCGOU47Uk/jnophPzDr2glv7YfBkhJ830XKSnRkzSDroLGpDItPDvptDVPr/pUrMLgDdbqBi55Gnw94RvA7/99++hznRozzSGiEVoMHVtZAlAnIwxU9X0an8eLl3OTOlNw70rZJGtEYQWNAt2q8Bfuag8PDKeNTqIxbRzKlhK5ZyfgPVL+GeaI5LELd10t4XOCIrm2ZIjT6fQ6zs6G1ornfMAv3CmBFlfaN3/zOY6Sb6BnaMu9vA47mXYF9YlxSiCUrpP/LU53sJkYw/ZH+nBD8Acm7OAq1TCgeUBFjFvYJOZZykkVMnrtC5R6tilLovXQYXKQQ+t8Nru+GHohJKC
  template:
    metadata:
      creationTimestamp: null
      name: nlp-inference-secrets
      namespace: nlp-inference
