apiVersion: v1
kind: Service
metadata:
  name: nlp-inference-api
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: nlp-inference-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.api.nodePort }}
