---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: metadata-postgres-secret
  namespace: metadata
spec:
  encryptedData:
    password: AgBsW/L/LVh+wqHH5YtPSFJ4U+hfX9DaPTHb9SE4KuKz+TiUTt0NmVh4+Rkd5fF3OLj8YPIn6WNrVkDH4RU5Dt+F9sHZo5u7E159bEYQtfpqjag8Sj/n/rpbteEaWPJpaXS8ymqGiTcLSB9qyI5uniypMv64AQ/PAPKMatfzzZDGVAuopAzNaxXcZ/6X4/04Gq7khnu4pFfNSFgITbX3kO1STqEiGJMZWC6Fr29sTo7JihD16/X/j2rEdaIc72f9W1KAmHbMxDyi6I1DgcSNsgxX6+VaFe2Ci62uC1UOkTjev9XQPTxaZ+7xBgPmpN+WBQmCkrkY/WRO9cjNErnqlafOEKRhTLPwoXqbba8j/02fNwPtjXGt3P1P5BhuDxmHi+m+iEHifcyDTw5vm/L2xCUsvl9hfQk+jxgQjp+XfqwGeKMmylOIpRWkjfkanZabAlZvYYactiK3JsQEuNzzdQguv29NKYSJFqdm+H2o1g15nogBGhAWn2e6b19Qiab2syinu+zevpA4aYmkk4tnXYNj9NtsMKMbAylm1bMsNKb55/QQb0XDGVqQoHjcLehYkoUwnucdMK2oQvuiV4xxP74dEttiA6baPA6lLsI37XVVz4S74/a0euTQhSSL8p2fPp13gOB13zARefKph5QOmPG9gJYIL5+QS7+PBBge3PU/+s0Qkj+meXeDJ7z3VQDTBJTOnK1xW9TDNsRPJekA3RzoZ83U+iKpCR8PEm0UM+TDDw==
  template:
    metadata:
      creationTimestamp: null
      name: metadata-postgres-secret
      namespace: metadata
