namespace: research-agent

api:
  image:
    repository: ghcr.io/ahembal/research-agent-api
    tag: b2cc39694224fb425bc811914525aae852b600e0   # replaced by CI with full SHA
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

streamlit:
  image:
    repository: ghcr.io/ahembal/research-agent-streamlit
    tag: b2cc39694224fb425bc811914525aae852b600e0   # replaced by CI with full SHA
  replicas: 1

ollama:
  image: ollama/ollama:latest
  model: llama3.1:8b
  resources:
    requests:
      memory: "18Gi"
      cpu: "2"
    limits:
      memory: "20Gi"
  pvc:
    storageClass: ceph-rbd
    size: 10Gi
  nodeSelector:
    kubernetes.io/hostname: quick-thrush

chromadb:
  pvc:
    storageClass: ceph-rbd
    size: 5Gi

ncbiEmail: researcher@example.com
