apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.ollama.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.ollama.pvc.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.chromadb.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.chromadb.pvc.size }}
