apiVersion: v1
kind: Service
metadata:
  name: research-agent-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: research-agent-api
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: research-agent-streamlit
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: research-agent-streamlit
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30651
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
